### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by JStika** [dravencms/dravencms#2]
Hi,

how can I test your dravencms under windows 10/xampp?
I got error when I execute "./bin/console orm:s:c":
Class 'Nette\Loaders\NetteLoader' not found.

**Comment by Salamek** [comment]
@JStika there is missing depedency in dravencms 1.0.3, fixed in 1.0.4 (https://github.com/dravencms/dravencms/commit/e7d9e8762c83142c50212de914b20019bac86422)

To fix you issue you can apply this patch (https://github.com/dravencms/dravencms/commit/e7d9e8762c83142c50212de914b20019bac86422) to your current installation (just one line added in composer.json) and then run `composer update`  or just delete your current dravencms install and follow README.md
